include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    unused_field: ignore
    no_leading_underscores_for_local_identifiers: ignore
    use_build_context_synchronously: ignore
    unused_local_variable: ignore
    unused_element: ignore
